apiVersion: v1
name: quorum-propose-validator
description: "Quorum: Proposes to add or remove a validator with the specified address."
version: 1.0.1
appVersion: latest
keywords:
  - bevel
  - ethereum
  - quorum
  - hyperledger
  - enterprise
  - blockchain
  - deployment
  - accenture
home: https://hyperledger-bevel.readthedocs.io/en/latest/
sources:
  - https://github.com/hyperledger/bevel
maintainers:
  - name: Hyperledger Bevel maintainers
    email: bevel@lists.hyperledger.org
