image:
  repository: ghcr.io/hyperledger/bevel-k8s-hooks
  tag: qgt-0.2.12
  pullPolicy: IfNotPresent
  pullSecret: ""

validators:
  consensusMethod: "istanbul_propose"
  auth: true # Set to 'true' to vote the candidate in and 'false' to vote them out
  # List of URLs of the existing validators
  existingValidators:
    # - "http://<test-1.yourDomain.com>"
    # - "http://<test-2.yourDomain.com>"
    # - "http://<test-3.yourDomain.com>"
    # - "http://<test-4.yourDomain.com>"
  # List of node addresses of the validators that need to be proposed
  proposeValidatorsAddr:
    # - "<0xnodeAddress-1>"
    # - "<0xnodeAddress-2>"
    # - "<0xnodeAddress-3>"
