name: Release Charts

on:
  workflow_dispatch:
    inputs:
      platformChoice:
        description: 'Release chart for specific platform'
        required: true
        default: 'all'
        type: choice
        options:
        - besu
        - fabric
        - indy
        - quorum
        - r3-corda
        - r3-corda-ent
        - substrate
        - shared
        - all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3.3
        with:
          version: v3.8.1

      - name: Install additional Helm repos
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
        
      - name: Release all charts
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

